#!/bin/sh
# ---- Comments inherited from PRE_BUILD times ----
# PRE_BUILD for rejected spells
#
# Modified 2002 Aug 23 05:10 by Derek Moyes <sorcerer@flamesnyper.com>
#   Default behavior changed to NOT AUTOMATICALLY install or update rejected
#     spells. This prevents silly third-party install scripts from halting a
#     sorcery update, while waiting for input.
#   Added test for UNATTEND_SAFE placeholder file in the spell. This file skips
#     the warning altogether & allows the spell to cast automatically. Simply
#     create an empty file named UNATTEND_SAFE in the spell's directory.
#   Check if spell installed routine added (thx to dufflebunk for bash help).
#   Comments added for future BASHers.
#   Warning text clarified & expanded.
#   Sorcery colors added.
# ---- End of comments ----

# Warn user about problems with spell.
function warn_rejected()
{
  local TEXT=$(
    cat <<EOF
${MESSAGE_COLOR}This spell is considered ${PROBLEM_COLOR}rejected${DEFAULT_COLOR}${MESSAGE_COLOR} because of the following reason:
${PROBLEM_COLOR}$REJECT${DEFAULT_COLOR}${MESSAGE_COLOR}.
Please view this software's website for more information: ${DEFAULT_COLOR}$WEB_SITE${MESSAGE_COLOR}.
You may continue casting the spell and it will still be tracked by Sorcery.
However, the software's installation process may have questions that need to be
answered and/or licensing agreements that must be agreed to.${DEFAULT_COLOR}
EOF
  )
  message "$TEXT"
}

# Ask if user wants to continue anyway. (defaults to NO), unless running in UNATTEND_SAFE mode.
function ask_continue_with_rejected()
{
  if spell_installed "$SPELL" && [ -e $SCRIPT_DIRECTORY/UNATTEND_SAFE ]; then
    message  "${MESSAGE_COLOR}$SPELL ${FILE_COLOR}is${MESSAGE_COLOR} installed,"      \
             " and has been determined to be ${FILE_COLOR}safe for unattended update" \
			 " ${DEFAULT_COLOR}${MESSAGE_COLOR}, so the prompt will be skipped.${DEFAULT_COLOR}"
    return
  fi

  message  "${MESSAGE_COLOR}Allowing the next question to timeout will choose" \
           " not to install this spell. This means that rejected spells"       \
		   " ${PROBLEM_COLOR}will not be installed or updated automatically."  \
		   " ${DEFAULT_COLOR}${MESSAGE_COLOR}If you want a rejected spell to"  \
		   " be installed or updated you must confirm your decision now or"    \
		   " cast the spell later.${DEFAULT_COLOR}"
	     
  if ! query  "CONTINUE casting?" n; then
    message "${MESSAGE_COLOR}You chose to stop the installation, or you let" \
	        " the prompt timeout. Maybe you'll be braver next time?${DEFAULT_COLOR}"
    exit 1
  fi

  message "${MESSAGE_COLOR}OK, here we go... you're on your own!${DEFAULT_COLOR}"
}
