--- makefile.old	2002-08-01 15:38:38.000000000 -0700
+++ makefile	2002-08-01 15:40:32.000000000 -0700
@@ -16,9 +16,9 @@
 LIBS =  -lX11 -lm
 
 # Silicon Graphics
-CFLAGS = -c -DDOBACK -DHASTIMER -DCOLOR_OFFSET=0.0
-FFLAGS =   
-LDR = f77 
+#CFLAGS = -c -DDOBACK -DHASTIMER -DCOLOR_OFFSET=0.0
+#FFLAGS =   
+#LDR = f77 
 
 # Ultrix, Dec Alpha, Linux ( and best start for Unix other than below )
 #
@@ -40,11 +40,11 @@
 #
 # On 64-bit Alpha-Linux add -mieee to the FFLAGS
 #
-#CFLAGS = -c -I/usr/X11R6/include -DDOBACK -DHASTIMER -DCOLOR_OFFSET=0.0
-#FC = g77
-#FFLAGS =
-#LIBS =  -L/usr/X11R6/lib -lX11 -lm
-#LDR = g77   
+CFLAGS = -c -I/usr/X11R6/include -DDOBACK -DHASTIMER -DCOLOR_OFFSET=0.0
+FC = g77
+FFLAGS =
+LIBS =  -L/usr/X11R6/lib -lX11 -lm
+LDR = g77   
 #
 
 #
