(

DATA="${INSTALL_ROOT}/usr/share/games/d2x"

prepare_install         &&
mkdir -p $DATA          &&
cp -f d2demo.ham $DATA  &&
cp -f d2demo.hog $DATA  &&
cp -f d2demo.pig $DATA  &&
cp -f descentg.ini $DATA

)  >  ${C_FIFO}  2>&1
