(

  prepare_install                               &&
  mkdir -p /usr/share/skype                     &&
  cp -ruv $SOURCE_DIRECTORY/* /usr/share/skype  &&
  ln -s /usr/share/skype/skype /usr/bin/skype 

) > $C_FIFO 2>&1
