#!/bin/sh

PROGRAM=/usr/bin/svscanboot
RUNLEVEL=3

. /etc/init.d/smgl_init

start()
{

  PSLIST=`ps ax`

  if ! echo $PSLIST| grep -q $PROGRAM; then
      echo -n "Starting svscan..."
      $PROGRAM &
      evaluate_retval
  else
      echo -n "svscan is already running..."
      print_status failure       
  fi
}

stop()
{
  echo -n "Stopping daemontools services..."
  killall  readproctitle svscanboot svscan
  /usr/bin/svc -xd /service/* /service/*/log &&
  evaluate_retval
}

usage()
{
  echo "Usage: $0 {start|stop}"
}
