(
ln -fs /usr/lib/libstdc++-*libc6.2-2*.so $SOURCE_DIRECTORY/libstdc++-libc6.1-1.so.2
cp /var/lib/sorcery/grimoire/z-rejected/netscape6/config.ini $SOURCE_DIRECTORY
./netscape-installer
ln -fs /usr/lib/libstdc++-*libc6.2-2*.so $INSTALL_DIRECTORY/libstdc++-libc6.1-1.so.2
cp /var/lib/sorcery/grimoire/z-rejected/netscape6/netscape6 /usr/bin/netscape6

)
