(

  prepare_install                         &&
  mkdir  -p      /usr/share/doc/${SPELL}  &&
  cp  bin/*      /usr/bin                 &&
  cp  -r  doc/*  /usr/share/doc/${SPELL}  &&
  cp  man/man1/*  /usr/share/man/man1

) > $C_FIFO 2>&1
