#!/bin/sh

export  LD_LIBRARY_PATH=/opt/gcc2/lib

cd   /usr/share/games/eClient

if  [  -x  fltk-eclient  ]
then
  ./fltk-eclient  $@
elif [  -x  elaunch  ]
then
  ./elaunch  $@
else
  echo  "No valid client found..."
fi

cd  -
