#not installing in /usr/lib because there could be some clashes with
#other libs.
./configure $ARK             \
--build=$BUILD               \
--prefix=/usr                \
--etcdir=/etc/root/          \
--libdir=/usr/lib/root/      \
--incdir=/usr/include/root   \
--datadir=/usr/share/root    \
--mandir=/usr/share/man/man1 \
$OPTS
