#!/bin/bash

PROGRAM=/usr/NX/bin/nxserver
RUNLEVEL=5

. /etc/init.d/smgl_init

start()
{
    $PROGRAM --start
}

stop()
{
    $PROGRAM --shutdown
}

restart()
{
    $PROGRAM --restart
}

status()
{
    $PROGRAM --status
}
