#!/bin/sh

echo -e "\n\nThe setiathome binary doesn't accept stop commands,\nBut it does record it's progress so if you 'kill' it it will restart 
at \
the same place as before.\nAfter you have setup your new account or configured this machine to use an existing account
you may CTRL ^C the running program then either use\n
telinit run smgl-setiathome {start|stop|restart} \n\tor just manually run \nsetiathome
(a regular script that returns the shell to the user)
Press <enter> to continue" &&
read &&
cd  /usr/share/setiathome &&
/usr/share/setiathome/setiathome  $@  
exit  0
