(

  ./configure  --prefix=/usr                     \
               --exec-prefix=/usr                \
               --sysconfdir=/etc                 &&
  make                                           &&
  prepare_install                                &&
  make    install

) > $C_FIFO 2>&1 
