(
  prepare_install            &&
  cp usr/bin/cgc /usr/bin/ &&
  cp -R usr/include/Cg /usr/include/ && 
  cp -R usr/include/CgFX /usr/include/ && 
  cp usr/lib/libCg*.so /usr/lib/ &&
  cp -R usr/local/Cg /usr/share/docs/ &&
  cp usr/share/man/man3/cg*.3 /usr/share/man/man3/
) > $C_FIFO 2>&1
